let name = "winnie";
console.log(name);
let age = 25;
console.log(age);
let num 1 = 10;
let num 2 = 20;
let sum = num 1 + num 2;
console.log(sum);
let difference = num 1 - num 2;
console.log(difference);
console.log("num 1 * num 2.");
console.log(num 1 / num 2);
console.log("num 1 % num 2.");
console.log(15% 4);
let x = true;
let y = false;
console.log(x && y);
let z = 11;
console.log(typeof z);
let a ="winnie";
console.log(typeof a);
