let name = "winnie";
console.log(name);
let age = 25;
console.log(age);
let num1 = 10;
let num2 = 20;
let sum = num1 + num2;
console.log(sum);
let difference = num1 - num2;
console.log(difference);
console.log("num1 * num2:");
console.log(num1 * num2);
console.log("num1 / num2:");
console.log(num1 / num2);
console.log("num1 % num2:");
console.log(num1 % num2);
let x = true;
let y = false;
console.log(x && y);
let z = 11;
console.log(typeof z);
let a ="winnie";
console.log(typeof a);
